spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_ADMIN_USERNAME}
    password: ${DB_ADMIN_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope:
              - profile_image
              - email
              - nickname
              - birthday
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: https://point-of-views.com/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      timeout: 3000ms

cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_ACCESS_KEY}
    s3:
      bucketName: bucket-uplus-127
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  token:
    secretKey: "urecapointofviewsurecapointofviewsurecapoin"

TMDb:
  access: ${TMDB_ACCESS_TOKEN}

firebase:
  config:
    path: firebase/firebase-service-account.json

toss:
  secret-key: ${TOSS_SECRET_KEY}

oauth:
  baseurl: https://point-of-views.com